---
version: "3.3"
services:
  raSpotify:
    image: keesromkes/rpi-spotify
    network_mode: host
    restart: always
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - "/mnt/share/daapd_music:/mnt/share/daapd_music"
    environment:
      - SPOTIFY_NAME=Jukebox
      - BACKEND_NAME=pipe
      - DEVICE_NAME=/mnt/share/daapd_music/spotify
